### PR TITLE
I have done a rewrite on the templates

### PR DESCRIPTION
**Pull request by kitten77**
added the templates to their own folders inside the app so that it will become easier to use the same apps on a later point in a different django project, same with some of the js

also found a few disturbing errors wiht the user list delete and such i am working on a complete user management app, if you wish to impletement the changes i did so that i could easly can pull of your updates and keep in sync that would be really nice

### CODE REVIEW

**Comment by ashwin31** [comment]
@kitten77 I appreciate your effort of moving js file to relevant apps.  see possibilities of creating new pull requests. I am happy to merge.

**Comment by kitten77** [comment]
I see there is very many things to debug in this code, just started a cleanup of imports that is unused.
My problem is that you pushed to master before i could do a complete cleanup of the codes you already had in your repo, so the files i have moved from template and static dosent have the fixes you pushed recently

**Comment by ashwin31** [comment]
Okay I pushed some changes now, and will not do any major changes till Monday.

**Comment by kitten77** [comment]
thanks :) 
i will make a clean pull request to you to implement during the weekend

**Comment by ashwin31** [comment]
okay

**Pull request closed without merging**
